[profile.default]
libs = ["lib"]
src = "contracts"
out = "build/out"
cache_path ="build/cache"

optimizer = true
optimizer_runs = 200
solc_version = "0.8.27"

remappings = [
    # Local files
    "@OrbitSphere-scripts/=script/",
    "@OrbitSphere-contracts/=contracts/",

    # External libraries
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
